// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZObKyLk_Cik0H_qJ-IGBQUOR3hhlFko',
    appId: '1:565193661532:web:804f0fa8dcf2e05ef89a99',
    messagingSenderId: '565193661532',
    projectId: 'univia-db582',
    authDomain: 'univia-db582.firebaseapp.com',
    storageBucket: 'univia-db582.firebasestorage.app',
    measurementId: 'G-80MBTDHFBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHf5CG8bgwhJKHNVhDUIxrEsZI3-z005g',
    appId: '1:565193661532:android:75f33d7fbeedd0bef89a99',
    messagingSenderId: '565193661532',
    projectId: 'univia-db582',
    storageBucket: 'univia-db582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80wqK9sZjYpBliOgVeas6WDYQPl8TgzM',
    appId: '1:565193661532:ios:137a8778f0251ea2f89a99',
    messagingSenderId: '565193661532',
    projectId: 'univia-db582',
    storageBucket: 'univia-db582.firebasestorage.app',
    iosBundleId: 'com.mycompany.dormi',
  );
}
